#!/usr/bin/env zsh

gfx=(assets/gfx/*.png(.))
fontchars=(assets/minifont/*.png(.))
total_asset_count=$((${#gfx}+${#fontchars}))

assetnames=(${(AU)gfx:t:r})
assetindex=0

for greatgreat in $assetnames; do
    printf -v assetdefines "%b#define ASSET_%s %d\n" ${assetdefines:-// Asset defines\\n} $greatgreat $assetindex
    ((assetindex++))
done
unset assetnames
unset assetindex

cat<<ASSET_HEADER>src/assets.h
// Generated by generate_assets_h.sh - do not modify
#pragma once
#define TOTAL_ASSET_COUNT ${total_asset_count}
static SDL_Texture* textures[TOTAL_ASSET_COUNT];
static const char* assets[TOTAL_ASSET_COUNT] = {
$(print ${(F)gfx[@]} | sed -E 's@^(.+)$@    "\1",@g')
$(print ${(F)fontchars[@]} | sed -E 's@^(.+)$@    "\1",@g')
};
${assetdefines}
static const size_t char_to_asset[256] = {
$(for byte in {0..255}; do printf -v fname assets/minifont/%04X.png ${byte}; if [[ -f ${fname} ]] { print -n "$((${#gfx}+${fontchars[(i)${fname}]}-1))" } else { print -n '0' }; print ','; done)
};
static const unsigned char asset_to_char[TOTAL_ASSET_COUNT] = {
$(for graphic in $gfx; do print '0,'; done)
$(for fontchar in $fontchars; do print "$(( 0x${fontchar:16:4} )),"; done)
};
ASSET_HEADER
