#!/usr/bin/env zsh

gfx=(assets/gfx/*.png(.))
fontchars=(assets/minifont/*.png(.))
sfx=(assets/sfx/*.wav(.))
gfx_asset_count=$((${#gfx}+${#fontchars}))
sfx_asset_count=${#sfx}

assetnames=(${(AU)gfx:t:r})
assetindex=0

for greatgreat in $assetnames; do
    printf -v assetdefines "%b#define ASSET_%s %d\n" ${assetdefines:-// Assets \(gfx\)\\n} $greatgreat $assetindex
    ((assetindex++))
done
assetnames=(${(AU)sfx:t:r})
assetindex=0
for greatgreat in $assetnames; do
    printf -v assetdefines "%b#define ASSET_%s %d\n" ${assetdefines:-// Assets \(sfx\)\\n} $greatgreat $assetindex
    ((assetindex++))
done

cat<<ASSET_HEADER>src/assets.h
// Generated by generate_assets_h.sh - do not modify
#pragma once
#define GFX_ASSET_COUNT ${gfx_asset_count}
#define SFX_ASSET_COUNT ${sfx_asset_count}
#define TOTAL_ASSET_COUNT GFX_ASSET_COUNT + SFX_ASSET_COUNT
static const char* assets[TOTAL_ASSET_COUNT] = {
$(print ${(F)gfx[@]} | sed -E 's@^(.+)$@    "\1",@g')
$(print ${(F)fontchars[@]} | sed -E 's@^(.+)$@    "\1",@g')
$(print ${(F)sfx[@]} | sed -E 's@^(.+)$@    "\1",@g')
};
static const uint32_t assetindices[TOTAL_ASSET_COUNT] = {
// gfx
$(for x in {0..$((gfx_asset_count-1))}; do print "$x,"; done)
// sfx
$(for x in {0..$((sfx_asset_count-1))}; do print "$x,"; done)
};
${assetdefines}
static const size_t char_to_asset[256] = {
$(for byte in {0..255}; do printf -v fname assets/minifont/%04X.png ${byte}; if [[ -f ${fname} ]] { print -n "$((${#gfx}+${fontchars[(i)${fname}]}-1))" } else { print -n '0' }; print ','; done)
};
static const unsigned char asset_to_char[GFX_ASSET_COUNT] = {
$(for graphic in $gfx; do print '0,'; done)
$(for fontchar in $fontchars; do print "$(( 0x${fontchar:16:4} )),"; done)
};
ASSET_HEADER
