/*
 * Shoot It! (c) Copyright 2026 Talon1024
 *
 * This file is part of Shoot It!
 *
 * Shoot It! is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * Shoot It! is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Shoot It!. If not, see <https://www.gnu.org/licenses/>.
 *
 * None of this code was generated by AI. However, some of it was copy/pasted
 * from the SDL3 examples <https://examples.libsdl.org/SDL3/>, which are in the
 * Public Domain.
 */

#define SDL_MAIN_USE_CALLBACKS 1  /* use the callbacks instead of main() */
#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>
#include <cstdint>
#include <cstring>
#include <array>
#include <utility> // for the 'swap' function
#include <emscripten.h>
#include "main.h"
#include "assets.h"

/* We will use this renderer to draw into this window every frame. */
static SDL_Window* window = nullptr;
static SDL_Renderer* renderer = nullptr;
static SDL_AsyncIOQueue* queue = nullptr;

/* This function runs once at startup. */
SDL_AppResult SDL_AppInit(void** appstate, int argc, char* argv[])
{
    SDL_SetAppMetadata("Shoot It!", "0.0", "io.github.Talon1024.ShootIt");

    if (!SDL_Init(SDL_INIT_VIDEO)) {
        SDL_Log("Couldn't initialize SDL: %s", SDL_GetError());
        return SDL_APP_FAILURE;
    }

    SDL_Rect screenRect {0, 0, VIEW_WIDTH, VIEW_HEIGHT};
#if not(__EMSCRIPTEN__)
    uint32_t primaryDisplayId = getPrimaryDisplay();

    if (primaryDisplayId == 0) {
        SDL_Log("No display found!");
        return SDL_APP_FAILURE;
    }

    if (!SDL_GetDisplayBounds(primaryDisplayId, &screenRect)) {
        SDL_Log("Could not get primary display size.");
    }
#endif
    if (!SDL_CreateWindowAndRenderer("Shoot It!", screenRect.w, screenRect.h, SDL_WINDOW_RESIZABLE | SDL_WINDOW_MAXIMIZED | SDL_WINDOW_FILL_DOCUMENT, &window, &renderer)) {
        SDL_Log("Couldn't create window/renderer: %s", SDL_GetError());
        return SDL_APP_FAILURE;
    }
    SDL_SetRenderLogicalPresentation(renderer, VIEW_WIDTH, VIEW_HEIGHT, SDL_LOGICAL_PRESENTATION_LETTERBOX);
    SDL_SetDefaultTextureScaleMode(renderer, SDL_SCALEMODE_PIXELART);
    SDL_HideCursor();

    queue = SDL_CreateAsyncIOQueue();
    if (!queue) {
        SDL_Log("Couldn't create async i/o queue: %s", SDL_GetError());
        return SDL_APP_FAILURE;
    }

    {
        for (uint32_t assetIndex = 0; assetIndex < TOTAL_ASSET_COUNT; assetIndex++) {
            const char* fname = assets[assetIndex];
            if (!loadAssetAsync(fname, assetIndex)) {
                return SDL_APP_FAILURE;
            }
        }
    }

    return SDL_APP_CONTINUE;  /* carry on with the program! */
}

uint32_t getPrimaryDisplay() {
    int numDisplays;
    uint32_t primaryDisplayId = 0;
    uint32_t* displays = SDL_GetDisplays(&numDisplays);
    if (numDisplays > 0) {
        primaryDisplayId = *displays; // Deref (copy) the first element.
    }
    SDL_free(displays);
    return primaryDisplayId;
}

inline bool loadAssetAsync(const char* asset, uint32_t index) {
    char* fullpath;
    SDL_asprintf(&fullpath, "%s/%s", SDL_GetBasePath(), asset);
    // It's much faster to store the asset index, since, that way, one can refer
    // directly to its slot instead of searching for it.
    bool result = SDL_LoadFileAsync(fullpath, queue, new uint32_t {index});
    if (!result) {
        SDL_Log("Unable to load asset %s: %s", asset, SDL_GetError());
    }
    SDL_free(fullpath);
    return result;
}

/* This function runs when a new event (mouse input, keypresses, etc) occurs. */
SDL_AppResult SDL_AppEvent(void* appstate, SDL_Event* event)
{
    if (event->type == SDL_EVENT_QUIT) {
        return SDL_APP_SUCCESS; // end the program, reporting success to the OS.
    }
    return SDL_APP_CONTINUE;  /* carry on with the program! */
}

int32_t getPNGYOffset(void* bufdata, size_t bufsize) {
    // Search for the grAb chunk - the sprite offsets for ZDoom PNGs.
    char* idatStart = (char*) memmem(
        bufdata, bufsize,
        "IDAT", 4
    );
    if (!idatStart) {
        SDL_Log("Not a valid PNG!");
        return 0;
    }
    size_t grabHaystackSize = idatStart - (char*) bufdata;
    // grAb comes before IDAT
    int32_t* grabStart = (int32_t*) memmem(
        bufdata, grabHaystackSize,
        "grAb", 4
    );
    if (!grabStart) {
        return 0;
    }
    int32_t* offsets = grabStart + 1;
    int32_t offsetX = SDL_Swap32BE(*offsets);
    int32_t offsetY = SDL_Swap32BE(*(offsets+1));
    return -offsetY; // negative Y offset = down
}

#define SPACE_WIDTH 5.0

void RasterFont::drawText(const char* text, float x, float y) const {
    size_t textLength = SDL_strlen(text);
    SDL_FRect charRect {x, y, 0.0, 0.0};
    for (size_t pos = 0; pos < textLength; pos++) {
        char curChar = text[pos];
        // Space to next character - 5 if space, width + 1 for kerning.
        size_t assetIndex = charInfo[curChar].asset;
        if (curChar == ' ') {
            charRect.x += SPACE_WIDTH;
            continue;
        } else if (assetIndex == 0) { continue; }
        charRect.w = charInfo[curChar].width;
        charRect.h = charInfo[curChar].height;
        charRect.y = y + charInfo[curChar].yoffset;
        SDL_RenderTexture(renderer, textures[assetIndex], nullptr, &charRect);
        charRect.x += charInfo[curChar].width + 1.0; // 1 pixel for kerning
    }
}

bool RasterFont::assignAsset(uint32_t assetIndex, const SDL_AsyncIOOutcome& outcome) {
    unsigned char cByte = asset_to_char[assetIndex];
    if (cByte < 33) { return false; }
    // Set up font character
    // Read width and height from IHDR
    uint32_t width = SDL_Swap32BE(*((uint32_t*)outcome.buffer + 4));
    uint32_t height = SDL_Swap32BE(*((uint32_t*)outcome.buffer + 5));
    // Read Y offset from grAb chunk
    // https://zdoom.org/wiki/GrAb
    int32_t yoffset = getPNGYOffset(outcome.buffer, (size_t) outcome.bytes_transferred);
    charInfo[cByte].asset = assetIndex;
    charInfo[cByte].width = (float) width;
    charInfo[cByte].height = (float) height;
    charInfo[cByte].yoffset = (float) yoffset;
    return true;
}

EM_JS(void, signalReady, (float* pDifficulty, bool* pNewGame), {
    window.parent.postMessage({op: "ready"});
    window.addEventListener("message", ev => {
        if ("op" in ev.data) { switch(ev.data.op) {
            case "start":
                console.log("Difficulty set to", ev.data.difficulty);
                setValue(pDifficulty, ev.data.difficulty, "float");
                setValue(pNewGame, 1, "i8");
                break;
                // TODO: more ops?
            }
        }
    });
});

EM_JS(void, signalStart, (), {
    window.parent.postMessage({op: "started", verb: "Defend!"});
});

EM_JS(void, signalDone, (int32_t won), {
    window.parent.postMessage({op: "done", win: !!won});
});

enum class MovementPattern {
    Straight,
    SquareRoot
};

#define NINE_BIT_MAX 511  // 512 - 1

class Speed {
public:
    bool reverseDirection : 1;
    bool onePixelPerXTics : 1;
    bool useSpeedB : 1; // used with onePixelPerXTics
    // Padding so the speeds and lifetime can all use the same amount of bits
    uint8_t padding : 2;
    // When onePixelPerXTics is true, the value calculated by moveAmount will
    // be 1 every speedA ticks, otherwise 0. If speedB is not zero, the
    // number of ticks used by the moveAmount to determine whether or not to
    // move the enemy will alternate between speedA and speedB. speedA can be
    // much larger to account for enemies spawned close to the center.
    uint16_t speedB : 9;
    uint16_t speedA : 9;
    int32_t moveAmount();
    Speed(uint16_t speedA = 0) : reverseDirection(false), onePixelPerXTics(false), useSpeedB(false), speedB(0), speedA(speedA), lifetime(0) {}
private:
    uint16_t lifetime : 9; // used for movement pattern
};

int32_t Speed::moveAmount() {
    if (!onePixelPerXTics) {
        // Pixels-per-tick movement
        return speedA * (2 * !!(reverseDirection) - 1);
    } else {
        // Ticks-per-pixel movement
        uint8_t speed = useSpeedB ? speedB : speedA;
        if (speed > 0 && speed == lifetime) { // Lifetime will be reset
            // P.S. I think I need a more accurately descriptive name than
            // "lifetime" :P
            // Alternate between the two speeds
            useSpeedB = speedB != 0 && !useSpeedB;
            // Reset lifetime
            lifetime = 0;
            return 1 * (2 * !!(reverseDirection) - 1);
        } else {
            lifetime += 1;
        }
    }
    return 0;
}

struct GameExplosion {
    SDL_Rect rect;
    uint8_t frame;
};

#define EXPLOSION_FRAME_COUNT 10

static const size_t explosionFrames[EXPLOSION_FRAME_COUNT] {
    ASSET_EXPLOD_1,
    ASSET_EXPLOD_2,
    ASSET_EXPLOD_3,
    ASSET_EXPLOD_4,
    ASSET_EXPLOD_5,
    ASSET_EXPLOD_6,
    ASSET_EXPLOD_7,
    ASSET_EXPLOD_8,
    ASSET_EXPLOD_9,
    ASSET_EXPLOD_A
};

struct GameEnemy {
    SDL_Rect rect;
    Speed speedX;
    Speed speedY;
};

struct GameBomb {
    SDL_Rect rect;
    Speed speedX;
    Speed speedY;
};

struct GameThingToDefend {
    SDL_Rect rect;
};

struct GameEventSpawnEnemy {
    uint16_t tick;
    uint16_t count;
};

struct GameEventSpawnBomb {
    uint16_t tick;
};

enum class GamePlayStatus {
    Playing,
    Win,
    Loss,
};

struct GameData {
    SDL_FPoint cursorf;
    SDL_Point cursor;
    // bool paused;
    // bool lmb;
    // bool lmbHeld;
    // Events should be sorted by tick so that they run in a series
    std::array<GameEventSpawnEnemy, MAX_EVENTS + 1> events;
    std::array<GameEventSpawnBomb, MAX_EVENTS + 1> bombSpawns;
    std::array<GameEnemy, MAX_EVENTS * 4 + 1> enemies;
    std::array<GameExplosion, MAX_EVENTS * 4 + 1> explosions;
    std::array<GameBomb, MAX_EVENTS * 4 + 1> bombs;
    uint32_t activeEnemies;
    uint32_t activeExplosions;
    uint32_t activeBombs;
    uint32_t totalEnemies;
    uint32_t killedEnemies;
    GamePlayStatus status;
    GameThingToDefend theFriend;
    // uint32_t eventMax;
    GameEventSpawnEnemy* curEvent;
    GameEventSpawnEnemy* lastEvent;
    GameEventSpawnBomb* curBombSpawn;
    GameEventSpawnBomb* lastBombSpawn;
    uint32_t tick;
    uint32_t second;
};

struct SoundResources {
    SDL_AudioSpec specs[SFX_ASSET_COUNT];
    uint8_t* buffers[SFX_ASSET_COUNT];
    uint32_t lengths[SFX_ASSET_COUNT];
};

// Functions called during various loading/game states
inline void frameLoading(SDL_Texture** textures, SoundResources& sounds, LoadState& loadState, RasterFont& font);
inline void frameLoadFail();
inline void frameLoadSuccess();
inline void frameWaitingToStart(SDL_Texture** textures, const RasterFont& font);
inline void frameGamePlay(SDL_Texture** resources, GameData& game, const RasterFont& font);
inline void frameGameWin(SDL_Texture** textures, const RasterFont& font);
inline void frameGameLoss(SDL_Texture** textures, const RasterFont& font);
inline void gameNew(GameData& game, const float& difficulty);

/* This function runs once per frame, and is the heart of the program.
 SAFETY: The renderer is most likely initialized.
 */
SDL_AppResult SDL_AppIterate(void* appstate)
{
    // The "static" keyword makes these variables global, but only accessible
    // within the scope of this function.
    static SDL_Texture* resources[GFX_ASSET_COUNT] = {};
    static SoundResources sounds = {};
    static LoadState loadState = LoadState::Loading;
    static GameState gameState = GameState::Loading;
    static RasterFont font(resources);
    static GameData game;
    static bool drawn = false;
    static bool paused = false;
    static bool newGame = false;
    static float difficulty = 0.0;
    if (newGame && loadState == LoadState::PostSuccess) {
        SDL_Log("Starting a new game! (difficulty: %.3f)", difficulty);
        gameNew(game, difficulty);
        gameState = GameState::Play;
        signalStart();
        newGame = false;
        drawn = false;
    }
    static uint64_t lastTickTime = 0;
    // How I got the mouse position before moving the logic into the frame function.
    /*
    float cursorX, cursorY;
    SDL_MouseButtonFlags mouseButtons = SDL_GetMouseState(&cursorX, &cursorY);
    SDL_RenderCoordinatesFromWindow(renderer, cursorX, cursorY, &cursorX, &cursorY);
    cursorX = roundf(cursorX);
    cursorY = roundf(cursorY);
    */
    switch (gameState) {
    case GameState::Play:
        if ((SDL_GetTicks() - lastTickTime) > GAME_TICK_TIME_MS) {
            frameGamePlay(resources, game, font);
            lastTickTime = SDL_GetTicks();
            switch(game.status) {
                case GamePlayStatus::Win:
                    gameState = GameState::Win;
                    break;
                case GamePlayStatus::Loss:
                    gameState = GameState::Loss;
                    break;
                default:
                    break;
            }
            drawn = false;
        }
        break;
    case GameState::Win:
        if (!drawn) {
            signalDone(1);
            frameGameWin(resources, font);
            drawn = true;
        }
        break;
    case GameState::Loss:
        if (!drawn) {
            signalDone(0);
            frameGameLoss(resources, font);
            drawn = true;
        }
        break;
    case GameState::Paused:
        gameState = GameState::Play;  // Not doing this rn
        /*
        // Draw everything drawn in the 'play' state, and then "Paused" on top.
        if (!drawn) {
            frameGamePlay(resources, game);
            font.drawText("Paused", 80, 80);
        }
        */
        break;
    case GameState::Loading:
        switch (loadState) {
        case LoadState::Loading:
            frameLoading(resources, sounds, loadState, font);
            break;
        case LoadState::Failure:
            frameLoadFail();
            return SDL_APP_FAILURE;
        case LoadState::Success:
            // From this point on, JavaScript has write access to 'difficulty'
            // and 'newGame'.
            signalReady(&difficulty, &newGame);
            frameLoadSuccess();
            loadState = LoadState::PostSuccess;
            break;
        case LoadState::PostSuccess:
            SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255);
            gameState = GameState::WaitingToStart;
            break;
        }
        break;
    case GameState::WaitingToStart:
        if (!drawn) {
            frameWaitingToStart(resources, font);
            drawn = true;
        }
        break;
    }
    return SDL_APP_CONTINUE;  /* carry on with the program! */
}

int SDLCALL sortEventByTick(const void* a, const void* b) {
    const GameEventSpawnEnemy* ea = (const GameEventSpawnEnemy*) a;
    const GameEventSpawnEnemy* eb = (const GameEventSpawnEnemy*) b;
    if (eb->tick == 0 && ea->tick != 0) {
        return -1;
    } else if (ea->tick == 0 && eb->tick != 0) {
        return 1;
    } else if (ea->tick < eb->tick) {
        return -1;
    } else if (ea->tick > eb->tick) {
        return 1;
    }
    return 0;
}

inline void gameNew(GameData& game, const float& difficulty) {
    game.totalEnemies = 0; // Do this first so that I can add to it in the loop.
    // ========== Set up enemy spawns ==========
    uint32_t numEvents = SDL_min(MAX_EVENTS, SDL_max(1, MAX_EVENTS * difficulty / 100.0));
    {
        GameEventSpawnEnemy* event = game.events.data();
        for (uint32_t curEventId = 0; curEventId < numEvents; curEventId++) {
            event->tick = SDL_rand(MAX_TICK - 75 * 5) + 1;
            event->count = SDL_rand(SDL_min(3, uint32_t(difficulty / 30.0))) + 1;
            game.totalEnemies += event->count;
            // TODO?: Balancing and polish!
            event += 1;
        }
    }
    SDL_qsort(game.events.data(), numEvents, sizeof(GameEventSpawnEnemy), sortEventByTick);
    game.curEvent = game.events.data();
    game.lastEvent = game.events.data() + numEvents;
    // Ensure events are sorted by tick
    // SDL_Log("Event ticks:");
    // for (uint32_t index = 0; index < numEvents; index++) {
    //     SDL_Log("%u", game.events[index].tick);
    // }
    // Bomb spawns should start at difficulty 60
    uint32_t numBombSpawns = SDL_min(MAX_EVENTS, SDL_max(0, difficulty / 10.0 - 5.0));
    {
        GameEventSpawnBomb* bombSpawn = game.bombSpawns.data();
        if (numBombSpawns > 0) {
            // Make bomb spawns evenly spaced for time
            uint32_t interval = MAX_TICK / (numBombSpawns+1);
            for (uint32_t curEventId = 1; curEventId <= numBombSpawns; curEventId++) {
                bombSpawn->tick = interval * curEventId;
                bombSpawn += 1;
            }
        }
    }
    game.curBombSpawn = game.bombSpawns.data();
    game.lastBombSpawn = game.bombSpawns.data() + numBombSpawns;
    // ========== Set up/clear other things ==========
    game.status = GamePlayStatus::Playing;
    game.activeEnemies = 0;
    game.killedEnemies = 0;
    game.activeExplosions = 0;
    game.activeBombs = 0;
    game.tick = 0;
    game.second = MAX_TICK / 75;
    // game.lmb = false;
    // game.lmbHeld = false;
    game.theFriend = {
        { // rect
            VIEW_WIDTH - 18,
            (VIEW_HEIGHT >> 1) - 8,
            16,
            16
        }
    };
}

void gameEnemySpawn(GameEnemy& enemy, const SDL_Rect friendRect);
inline void gameEnemyMove(GameEnemy& enemy);
inline void gameEnemyKill(GameData& game, uint32_t curEnemy);
inline void gameBombSpawn(GameBomb& bomb);
inline void gameBombMove(GameBomb& bomb);
inline void gameBombKill(GameData& game, uint32_t curBomb);

// Render the game every tic
inline void frameGamePlay(SDL_Texture** resources, GameData& game, const RasterFont& font) {
    SDL_FRect renderRect;
    SDL_Rect collision;
    // ========== Get mouse position ==========
    SDL_MouseButtonFlags mouseButtons = SDL_GetMouseState(&game.cursorf.x, &game.cursorf.y);
    static bool lmb = false; // Must be static for lmbHeld to work properly
    bool lmbHeld = lmb && (mouseButtons & SDL_BUTTON_LEFT);
    lmb = mouseButtons & SDL_BUTTON_LEFT;
    bool shoot = (lmb && !lmbHeld);
    bool shotHit = false;
    SDL_RenderCoordinatesFromWindow(renderer, game.cursorf.x, game.cursorf.y, &game.cursorf.x, &game.cursorf.y);
    game.cursorf.x = SDL_roundf(game.cursorf.x);
    game.cursorf.y = SDL_roundf(game.cursorf.y);
    game.cursor.x = game.cursorf.x;
    game.cursor.y = game.cursorf.y;
    // ========== Go through events ==========
    if (game.curEvent < game.lastEvent && game.curEvent->tick <= game.tick) {
        SDL_Log("Spawn event at tick %d", game.curEvent->tick);
        for (uint32_t spawnNum = 0; spawnNum < game.curEvent->count; spawnNum++) {
            gameEnemySpawn(game.enemies[game.activeEnemies], game.theFriend.rect);
            game.activeEnemies += 1;
        }
        game.curEvent += 1;
    }
    if (game.curBombSpawn < game.lastBombSpawn && game.curBombSpawn->tick <= game.tick) {
        SDL_Log("Bomb spawn event at tick %d", game.curEvent->tick);
        gameBombSpawn(game.bombs[game.activeBombs]);
        game.activeBombs += 1;
        game.curBombSpawn += 1;
    }
    // ========== Process enemies ==========
    for (int32_t curEnemy = game.activeEnemies-1; curEnemy >= 0; curEnemy--) {
        // ========== Move enemies ==========
        gameEnemyMove(game.enemies[curEnemy]);
        // ========== Check for collisions with Mr. Green ==========
        if (SDL_GetRectIntersection(&game.enemies[curEnemy].rect, &game.theFriend.rect, &collision)) {
            game.status = GamePlayStatus::Loss;
        }
        // shotHit prevents multi-kills
        if (shoot && !shotHit && SDL_PointInRect(&game.cursor, &game.enemies[curEnemy].rect)) {
            gameEnemyKill(game, curEnemy);
            shotHit = true;
        }
    }
    // ========== Process bombs ==========
    for (int32_t curBomb = game.activeBombs-1; curBomb >= 0; curBomb--) {
        // ========== Move bombs ==========
        gameBombMove(game.bombs[curBomb]);
        // shotHit prevents multi-kills
        if (shoot && !shotHit && SDL_PointInRect(&game.cursor, &game.bombs[curBomb].rect)) {
            gameBombKill(game, curBomb);
            shotHit = true;
        }
    }
    // ========== Remove explosions at the end of their animation ==========
    for (int32_t curExpl = game.activeExplosions-1; curExpl >= 0; curExpl--) {
        if (game.explosions[curExpl].frame == EXPLOSION_FRAME_COUNT) {
            // Swap current explosion with the last
            std::swap(game.explosions[curExpl], game.explosions[game.activeExplosions-1]);
            // and remove it
            game.activeExplosions -= 1;
        }
    }
    if (game.tick % 75 == 0) {
        game.second -= 1;
    }
    // ========== Check for win/loss ==========
    if (game.killedEnemies == game.totalEnemies) {
        game.status = GamePlayStatus::Win;
    } else if (game.tick > MAX_TICK) {
        game.status = GamePlayStatus::Loss;
    }
    // ========== Render background ==========
    SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255);
    SDL_RenderTexture(renderer, resources[ASSET_BG], nullptr, nullptr); // bg
    // ========== Render game stuff ==========
    // Friend
    SDL_RectToFRect(&game.theFriend.rect, &renderRect);
    SDL_RenderTexture(renderer, resources[ASSET_F_FRIEND], nullptr, &renderRect);
    // Foes
    for (uint32_t curEnemy = 0; curEnemy < game.activeEnemies; curEnemy++) {
        SDL_RectToFRect(&game.enemies[curEnemy].rect, &renderRect);
        SDL_RenderTexture(renderer, resources[ASSET_F_ENEMY], nullptr, &renderRect);
    }
    // Explosions
    for (uint32_t curExpl = 0; curExpl < game.activeExplosions; curExpl++) {
        SDL_RectToFRect(&game.explosions[curExpl].rect, &renderRect);
        SDL_RenderTexture(renderer, resources[explosionFrames[game.explosions[curExpl].frame]], nullptr, &renderRect);
        game.explosions[curExpl].frame += 1;
    }
    // Bombs
    for (uint32_t curBomb = 0; curBomb < game.activeBombs; curBomb++) {
        SDL_RectToFRect(&game.bombs[curBomb].rect, &renderRect);
        SDL_RenderTexture(renderer, resources[ASSET_F_BOMB], nullptr, &renderRect);
    }
    // Crosshair
    renderRect = {
        game.cursor.x - 4.0f,
        game.cursor.y - 4.0f,
        7.0f, 7.0f
    };
    SDL_RenderTexture(renderer, shoot ? resources[ASSET_X_GHAIR] : resources[ASSET_X_OHAIR], nullptr, &renderRect);
    // Timer
    static char timerText[5] = {0}; // Time left: 0:45 (also static to reduce work)
    SDL_snprintf(timerText, 5, "0:%02u", game.second);
    font.drawText(timerText, VIEW_WIDTH - 20, 1.0);
    // Done with this frame
    SDL_RenderPresent(renderer);
    game.tick += 1;
}

void gameEnemySpawn(GameEnemy& enemy, const SDL_Rect friendRect) {
    // WIP!
    int32_t x = -15;
    int32_t y = SDL_rand(VIEW_HEIGHT - 24) + 8;
    // int32_t y = friendRect.y;
    int32_t speed = SDL_rand(3) + 1;
    // Aim for the center of the "friend".
    int32_t rise = y - friendRect.y;
    int32_t run  = friendRect.x - x;
    Speed speedX {}, speedY {};
    speedX.speedA = SDL_min(speed, NINE_BIT_MAX);
    speedX.onePixelPerXTics = false;
    speedX.reverseDirection = (x < 0);
    speedX.useSpeedB = false;
    // run/rise is the same as 1/rise/run
    double slope = rise == 0 ? 0.0 : SDL_fabs((double)run / rise / speed);
    double slopeInt;
    double slopeReal = SDL_modf(slope, &slopeInt);
    // calculate speed A and B
    speedY.speedA = (uint16_t)SDL_min(NINE_BIT_MAX, SDL_floor(slope));
    speedY.speedB = (uint16_t)SDL_min(NINE_BIT_MAX, slopeReal == 0.0 ? 0.0 : SDL_floor(slope * (0.5 + 0.5 * slopeReal)));
    // SDL_Log("slope, speedY A and B: %.4f %u %u", slope, speedY.speedA, speedY.speedB);
    speedY.onePixelPerXTics = true;
    speedY.reverseDirection = (rise < 0);
    speedY.useSpeedB = false;
    enemy = {
        { // rect
            // x y w h
            x, y,
            16, 16
        },
        speedX, // speedX
        speedY, // speedY
    };
}

inline void gameEnemyMove(GameEnemy& enemy) {
    enemy.rect.x += enemy.speedX.moveAmount();
    enemy.rect.y += enemy.speedY.moveAmount();
}

inline void gameEnemyKill(GameData& game, uint32_t curEnemy) {
    // Add an explosion where this enemy once was
    game.explosions[game.activeExplosions] = {
        game.enemies[curEnemy].rect, // rect (copy from enemy)
        0 // frame
    };
    game.activeExplosions += 1;
    // Swap current enemy with the last active enemy so it can be easily
    // removed.
    std::swap(game.enemies[curEnemy], game.enemies[game.activeEnemies-1]);
    game.killedEnemies += 1;
    game.activeEnemies -= 1;
}

inline void gameBombSpawn(GameBomb& bomb) {
    int32_t x = -15;
    int32_t y = SDL_rand(VIEW_HEIGHT - 24) + 8;
    Speed speedX {1};
    speedX.reverseDirection = (x < 0);
    Speed speedY {1};
    bomb.rect = {
        x, y, 16, 16
    };
    bomb.speedX = speedX;
    bomb.speedY = speedY;
}

inline void gameBombMove(GameBomb& bomb) {
    #define BOTTOM_EDGE VIEW_HEIGHT - 16
    if (bomb.rect.y <= 0 || bomb.rect.y >= BOTTOM_EDGE) {
        bomb.speedY.reverseDirection = !bomb.speedY.reverseDirection;
    }
    // move
    bomb.rect.x += bomb.speedX.moveAmount();
    bomb.rect.y += bomb.speedY.moveAmount();
}

inline void gameBombKill(GameData& game, uint32_t curBomb) {
    game.explosions[game.activeExplosions] = {
        game.bombs[curBomb].rect, // rect (copy from bomb)
        0 // frame
    };
    game.activeExplosions += 1;
    for (uint32_t curEnemy = 0; curEnemy < game.activeEnemies; curEnemy++) {
        // Explode ALL the enemies >:)
        game.explosions[game.activeExplosions] = {
            game.enemies[curEnemy].rect, // rect (copy from enemy)
            0 // frame
        };
        game.activeExplosions += 1;
    }
    game.killedEnemies += game.activeEnemies;
    game.activeEnemies = 0;
    std::swap(game.bombs[curBomb], game.bombs[game.activeBombs-1]);
    game.activeBombs -= 1;
}

inline void frameGameWin(SDL_Texture** textures, const RasterFont& font) {
    SDL_RenderTexture(renderer, textures[ASSET_BG], nullptr, nullptr);
    font.drawText("Mr. Green is safe!", 70.0, 75.0);
    SDL_RenderPresent(renderer);
}

inline void frameGameLoss(SDL_Texture** textures, const RasterFont& font) {
    SDL_RenderTexture(renderer, textures[ASSET_BG], nullptr, nullptr);
    font.drawText("Mr. Green died...", 70.0, 75.0);
    SDL_RenderPresent(renderer);
}

// For the rectangle that flashes during the loading sequence
// ==========================================================
// Size: 20x20
//
// X position:
// 240 / 2 = 120
// 120 - 10 = 110
//
// Y position:
// 160 * (3/4) = 120
// 120 - 10 = 110
static const SDL_FRect loadRect {110., 110., 20., 20.};

// "textures" is filled in with the successfully loaded textures
// "loadState" is filled in with success or failure
// "font" has assets assigned to bytes as the character images are loaded
inline void frameLoading(SDL_Texture** textures, SoundResources& sounds, LoadState& loadState, RasterFont& font) {
    static uint32_t assetsLoaded = 0;
    SDL_AsyncIOOutcome outcome;
    SDL_SetRenderDrawColor(renderer, 0, 0, 0, 255);
    if (SDL_GetAsyncIOResult(queue, &outcome)) {
        uint32_t assetIndex = *(uint32_t*)outcome.userdata;
        if (outcome.result == SDL_ASYNCIO_COMPLETE) {
            SDL_IOStream* dataStream = SDL_IOFromConstMem(
                outcome.buffer,
                (size_t) outcome.bytes_transferred
            );
            if (SDL_Surface* surf = SDL_LoadPNG_IO(dataStream, false)) {
                font.assignAsset(assetIndex, outcome);
                textures[assetIndex] = SDL_CreateTextureFromSurface(renderer, surf);
                if (!textures[assetIndex]) {
                    SDL_Log("Couldn't create texture! %s", SDL_GetError());
                    loadState = LoadState::Failure;
                }
                SDL_DestroySurface(surf);
                assetsLoaded++;
            } else {
                assetIndex -= GFX_ASSET_COUNT;
                if (SDL_LoadWAV_IO(dataStream, false, &sounds.specs[assetIndex], &sounds.buffers[assetIndex], &sounds.lengths[assetIndex])) {
                    assetsLoaded++;
                }
            } /*else {
                SDL_Log("%s", SDL_GetError());
                loadState = LoadState::Failure;
            }*/
            SDL_free(outcome.buffer);
            // Part of SDL_LoadFileAsync
            // SDL_CloseAsyncIO(outcome.asyncio, true, queue, new uint32_t {CLOSE_FILE});
        } else if (outcome.result == SDL_ASYNCIO_FAILURE) {
            SDL_Log("Could not load asset %s: %s", assets[assetIndex], SDL_GetError());
            loadState = LoadState::Failure;
        }
        if (assetsLoaded == GFX_ASSET_COUNT) {
            // finished loading!
            loadState = LoadState::Success;
        }
    }

    SDL_RenderClear(renderer);
    // SDL_GetTicks() returns ms since program start
    // 500 ms is half a second
    // 511 ms is very close
    // Number & 511 = number % 511
    // 511 >> 1 = 255 (the maximum for a u8)
    uint8_t shade = (uint8_t)((SDL_GetTicks() & 511) >> 1);
    // Assets (like font characters) are not loaded yet, so just show a
    // square as a placeholder.
    SDL_SetRenderDrawColor(renderer, shade, shade, shade, 255);
    SDL_RenderFillRect(renderer, &loadRect);
    SDL_RenderPresent(renderer);
}

inline void frameLoadFail() {
    SDL_RenderClear(renderer);
    // Red square
    SDL_SetRenderDrawColor(renderer, 180, 0, 0, 255);
    SDL_RenderFillRect(renderer, &loadRect);
    SDL_RenderPresent(renderer);
}

inline void frameLoadSuccess() {
    SDL_RenderClear(renderer);
    SDL_SetRenderDrawColor(renderer, 0, 180, 0, 255);
    SDL_RenderFillRect(renderer, &loadRect);
    SDL_RenderPresent(renderer);
}

// "textures" is used to reference a texture
// "font" is used to make it easier to reference font character textures
inline void frameWaitingToStart(SDL_Texture** textures, const RasterFont& font) {
    SDL_SetRenderDrawColor(renderer, 0, 0, 0, 255);
    SDL_RenderClear(renderer);
    SDL_SetRenderDrawColor(renderer, 255, 255, 255, 255);
    SDL_RenderTexture(renderer, textures[ASSET_BG], nullptr, nullptr);
    font.drawText("Get Ready...", 90, 77);
    SDL_RenderPresent(renderer);
}

/* This function runs once at shutdown. */
void SDL_AppQuit(void* appstate, SDL_AppResult result)
{
    /* SDL will clean up the window/renderer for us. */
}
