/*
 * Shoot It! (c) Copyright 2026 Talon1024
 *
 * This file is part of Shoot It!
 *
 * Shoot It! is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * Shoot It! is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Shoot It!. If not, see <https://www.gnu.org/licenses/>.
 *
 * None of this code was generated by AI. However, some of it was copy/pasted
 * from the SDL3 examples <https://examples.libsdl.org/SDL3/>, which are in the
 * Public Domain.
 */

#pragma once
#include <cstdint>
#include <SDL3/SDL.h>

#define VIEW_WIDTH 240
#define VIEW_HEIGHT 160

enum class LoadState {
    Loading,
    Failure,
    Success,
    PostSuccess, // So that the 'ready' message is only sent once.
};

enum class GameState {
    Loading,
    WaitingToStart,
    Play,
    Paused, // Needed?
    Win,
    Loss,
};

// 60+ FPS
#define GAME_TICK_TIME_MS 15

// Data for a raster font
class RasterFont {
private:
    struct FontCharInfo {
        size_t asset;
        float width;
        float height;
        float yoffset;
    } charInfo[256];
    // char name[16];  // For multiple font support
public:
    RasterFont() : charInfo{}{}
    void drawText(const char* text, float x, float y) const;
    bool assignAsset(uint32_t assetIndex, const SDL_AsyncIOOutcome& outcome);
};

uint32_t getPrimaryDisplay();
SDL_Texture* loadAsset(SDL_Renderer* renderer, const char* fname);
bool loadAssetAsync(const char* asset, uint32_t index);
int32_t getPNGYOffset(void* bufdata, size_t bufsize);
inline bool isPNG(void* data);
